[package]
authors = ["Shane Snover <ssnover95@gmail.com"]
name = "atmospheric-sensor-nrf52"
edition = "2018"
version = "0.1.0"

[dependencies]
cortex-m = "0.7.1"
cortex-m-rt = "0.6.13"
nrf52840-hal = "0.11.0"
embedded-hal = "0.2.4"
infrastructure = { path = "../infrastructure" }