[package]
name = "linux-sensor-client"
version = "0.1.0"
edition = "2018"

[dependencies]
cobs = "0.1.4"
postcard = "0.7"
serialport = "^4.0"
serial-protocol = { path = "../serial-protocol" }
tokio = { version = "^1.6", features = ["fs", "io-util", "macros", "rt-multi-thread", "signal", "time"]}